/*
 * Automatically generated C config: don't edit
 * F9 Microkernel Configurations
 */
#ifndef AUTOCONF_H_
#define AUTOCONF_H_
#define CONFIG_DEBUG_DEV_UART 1
#define CONFIG_KTIMER_TICKLESS_COMPENSATION 0
#define CONFIG_KIP_EXTRA_SIZE 128
#define CONFIG_KDB 1
#define CONFIG_LARGEST_FPAGE_SHIFT 16
#define CONFIG_INTR_THREAD_MAX 256
#define CONFIG_DBGPORT_USE_USART4 1
#define CONFIG_SMALLEST_FPAGE_SHIFT 8
#define CONFIG_KPROBES 1
#define CONFIG_MAX_KT_EVENTS 64
#define CONFIG_MAX_ASYNC_EVENTS 32
#define CONFIG_MAX_ADRESS_SPACES 16
#define CONFIG_KTIMER_MINTICKS 128
#define CONFIG_STDIO_USE_DBGPORT 1
#define CONFIG_KTIMER_HEARTBEAT 65536
#define CONFIG_KTIMER_TICKLESS 1
#define CONFIG_SYMMAP 1
#define CONFIG_MAX_THREADS 32
#define CONFIG_PANIC_DUMP_STACK 1
#define CONFIG_MAX_FPAGES 256
#define CONFIG_DEBUG 1
#define CONFIG_KTIMER_TICKLESS_INT_COMPENSATION 0
#endif /* AUTOCONF_H_ */
